### ISSUE TITLE
Id for provider 'CIRC' is in the providers.csv (on the spec repo), but not in the code.

### ISSUE THREAD

**Issue by jaimeventura** [lacuna-tech/mds-core#577]
Id for provider 'CIRC' is in the providers.csv (on the spec repo), but not in the code.

The Circ provider is defined here:
https://github.com/openmobilityfoundation/mobility-data-specification/blob/dev/providers.csv

But we found that is not in the [code](https://github.com/lacuna-tech/mds-core/blob/develop/packages/mds-providers/index.ts).

Can you please add this provider (or, even better, could the code could read that  file)?

Thank you.

**Comment by avatarneil** [comment]
Hi @jaimeventura, thanks for raising this issue! I just cut a PR #580 to add the Circ Provider entry. I agree that reading from the `providers.csv` would probably be ideal, but I'd like to resolve the immediate issue first and then follow-up with that later when I have some more bandwidth. Would you mind filing a separate issue in this repo for using the OMF's `providers.csv` instead of the hardcoded values? Thanks!

**Comment by avatarneil** [comment]
Resolved by #580, another issues should be made for importing the providers CSV.
