### ISSUE TITLE
Kafka, NATS, asynchronous processing – any documentation?

### ISSUE THREAD

**Issue by mrsimpson** [lacuna-tech/mds-core#883]
Dear MDS Core devs,

we are currently taking our first steps towards an implementation of MDS-core and are looking at the individual services.
Specifically, we are currently interested in the regulatory processes, namely `geography` and `policy`. 
While doing this, we understood that there's a [need for Kafka](https://github.com/lacuna-tech/mds-core/blob/develop/packages/mds-policy-service/service/provider.ts#L86). We had not seen that component in the high level architecture, but only a small one not in [mds-stream](https://github.com/lacuna-tech/mds-core/blob/develop/packages/mds-stream/README.md).

Is there any further information on how which of these streaming services (NATS and Kafka) are being used? There are much fewer usages of NATS in the code compared to Kafka, so I assume they are not equally usable alternatives.

We'd very (!) much appreciate insights into how you architected this project!

Best regards from Germany, 
Oliver

**Comment by avatarneil** [comment]
Hi @mrsimpson, thanks for posting this question! Right now we don't have substantial documentation around our usage of NATS/Kafka, but I can take a stab at answering a few questions here...

A few thoughts on NATS:
We've found NATS useful in cases where we need to deliver data between things extremely quickly, and don't need to worry about durability/persistence and delivery guarantees. NATS is extremely lightweight (uses very little resources) and low latency, but doesn't have any persistence (messages are entirely ephemeral, and only get passed through in-memory), so it's inadequate for any cases where there need to be delivery guarantees and replay-ability.

A few thoughts on Kafka:
We've found Kafka useful in cases where we need to deliver data between highly decouples services, and _do_ need to worry about durability/persistence and delivery guarantees. Kafka uses a commit-log system, which enables write (ensuring the write succeeds) & delivery (ensuring subscribed consumers have consumed) guarantees. Unfortunately, Kafka is a bit slower than NATS, so sometimes we'll use NATS in addition to (or in lieu) of Kafka, depending on the use case.

Now, to your questions around NATS/Kafka for Policy & Geography... I recently added Kafka into Policy so, so we could have a listener (external to mds-core) picking up new policies and updating some caches accordingly. Looking now, I realize I didn't make this _optional_, so that's probably why you're running into some issues! I'll cut a PR this morning making Policy Kafka writes dependent on the presence of the `KAFKA_HOST` environment variable, so if you have no need for Kafka, it'll be entirely optional.

**Comment by avatarneil** [comment]
@mrsimpson I just opened https://github.com/lacuna-tech/mds-core/pull/884 to make Kafka writes optional for the Policy Service! 

I'll cut an additional PR adding some notes to mds-stream about the usage of Kafka vs NATS.

**Comment by avatarneil** [comment]
@mrsimpson Another PR for you to check out! https://github.com/lacuna-tech/mds-core/pull/885 Please let me know if these resolve this issue, or if you have any further questions.

Thanks!

**Comment by mrsimpson** [comment]
Dear @avatarneil , 

Thanks for the elaboration so far! Since it was not optional so far I *guessed* that you were using Kafka for inter-microservice-communication as well (e. g. so that the compliance service could own a cache to be invalidated on policy publishing). Now that this has been sorted out, it complies better to my own understanding: Use Kafka for external consumers (e. g. mobility service providers) 👍 
With respect to NATS: It's been some time I've been looking into it, but NATS definitely had some support for persistent state. I now read that they deprecated `nats-streaming-server`, but with [JetStream](https://docs.nats.io/nats-concepts/jetstream) there is a drop-in-successor including retention policies and replay-ability.
NATS being so efficient and easy to set up, it would have been my choice for inter-service-communication.

I'm curious to understand how you're dealing with async. At the moment, there are more questions than answers on my end (e. g. I wonder what you do in case of failed commits after you published the policy to Kafka: There's the `beforeCommit`, but no undo in an `afterFailedCommit`), but having a brain full of questions marks is not unusual when you try to get a grip on a non-trivial application ;)

**Comment by mrsimpson** [comment]
@avatarneil thanks for the change on the readme in #885! Though I am in doubt about NATS ephemerality (does this word actually exist in English?), the information you added elaborates very well how you are utilizing the two!

**Comment by avatarneil** [comment]
@mrsimpson Yes, NATS-Streaming (STAN) adds a lot of the features which vanilla NATS does not have! We ran into a whole host of issues with NATS Streaming in the early days of MDS-Core, and ended up using Kafka because we found it easier to work with. There is also generally better support for Kafka than NATS in some serious computational frameworks (e.g. Apache Flink/Spark). 

JetStream is very interesting. When I was exploring it a couple years ago, it was still in its infancy and insufficient for production applications, but it looks like it's production-ready now! Many of my claims about NATS may be untrue in a world where JetStream is being used under-the-hood, but my operating assumption is that it hasn't been well adopted yet (I know at the very least we aren't using JetStream internally yet).

And indeed, I think 'ephemerality' is a word in English! What a strange language. 

One thing I want to clarify is what I mean by 'external consumers' in this context, and perhaps I should update my PR accordingly. By 'external' I mean 'not in mds-core', or 'not in Typescript'. For example, if you were running a data pipeline which was processing messages via something like Flink or Spark, I would consider those to be 'external' consumers. I _suppose_ Kafka does have some support for ACLs (Access Control Lists), but I would not look to Kafka as a means of distributing data outside of a VPC.

**Comment by avatarneil** [comment]
@mrsimpson As far as the `beforeCommit` behavior, if a `beforeCommit` throws, then the default behavior in TypeORM is to abort the current transaction! There are some tests in mds-policy-service that demonstrate this behavior.

**Comment by mrsimpson** [comment]
@avatarneil Yes, I am aware of that!
Consistency in a distributed system is tricky, and I was surprised to see you publish to Kafka before the commit is done. I expect the TypeORM-abort not to cancel the Kafka message being published, or does it?
Therefore, I expected this publishing to be done `afterSave`

**Comment by mrsimpson** [comment]
Thanks for the precision on "external consumers". Kafka (like all other zookeeper-enabled Apache-Tools, _I guess_) [do feature some ACL mechanism](https://docs.confluent.io/platform/current/kafka/authorization.html#kafka-authorization).
Anyway, as far as the MDS is concerned, there's not specification for push-mechanisms anyway...

**Comment by avatarneil** [comment]
@mrsimpson Aha, I see what you mean around the consistency!

So the way I've thought about the order of operations is something like this:
1. Open the DB transaction, attempt to publish the policy. If this would fail from the db, then this would throw an error, and abort the callstack.
2. Attempt to publish to kafka. If this fails, then this would throw an error, and abort the callstack.
3. Commit the DB transaction. The failure criteria for a Postgres COMMIT is pretty limited I think, and we'd be very unlikely to run into it here with such a trivial operation. If it did fail, however, then step 2 (publishing to Kafka) would have indeed completed, without the policy being marked as published in the database.

Hopefully that helps explain my thought process a bit! Gotta love asynchronous operations and having to put data in multiple places at once ^_^

**Comment by mrsimpson** [comment]
@avatarneil with 1) you are referring to [the business driven validations in the policy repository](https://github.com/lacuna-tech/mds-core/blob/develop/packages/mds-policy-service/repository/index.ts#L384-L398) prior to the db transaction being opened, right?
The SQL commit failing is very unlikely, unless there's a failure in *very* low leveled components, such as a disk. Oh wait, did we not have an EBS outage last October 😬  ?

Anyway, I guess I'm stressing you too much about veeeery detailed questions – keep on the good work!

Oliver

P.s.: Having written the last sentence, don't expect not to find nitpicking questions about other parts in the near future. But hopefully we should soon™️ be able to understand enbough to raise PRs instead of issues ;)

**Comment by avatarneil** [comment]
@mrsimpson That is indeed what I'm referring to :)

You're not stressing me out at all, your questions and insights are very thoughtful, and I appreciate them! Feel free to keep them coming. If you've got things you're curious to discuss outside of the context of an issue, I can see about spinning up a Github discussions section perhaps, that could be cool! 

Have a great day!

**Comment by avatarneil** [comment]
@mrsimpson https://github.com/lacuna-tech/mds-core/discussions now exists, for future reference!
